//>>built
require({cache:{"dijit/_WidgetBase":function(){define("dijit/_WidgetBase","require,dojo/_base/array,dojo/aspect,dojo/_base/config,dojo/_base/connect,dojo/_base/declare,dojo/dom,dojo/dom-attr,dojo/dom-class,dojo/dom-construct,dojo/dom-geometry,dojo/dom-style,dojo/has,dojo/_base/kernel,dojo/_base/lang,dojo/on,dojo/ready,dojo/Stateful,dojo/topic,dojo/_base/window,./Destroyable,./registry".split(","),function(h,j,i,c,a,g,e,l,f,b,n,d,k,p,o,r,s,w,x,t,y,q){function u(m){return function(a){l[a?"set":"remove"](this.domNode,
m,a);this._set(m,a)}}k.add("dijit-legacy-requires",!p.isAsync);k("dijit-legacy-requires")&&s(0,function(){h(["dijit/_base/manager"])});var v={};return g("dijit._WidgetBase",[w,y],{id:"",_setIdAttr:"domNode",lang:"",_setLangAttr:u("lang"),dir:"",_setDirAttr:u("dir"),textDir:"","class":"",_setClassAttr:{node:"domNode",type:"class"},style:"",title:"",tooltip:"",baseClass:"",srcNodeRef:null,domNode:null,containerNode:null,ownerDocument:null,_setOwnerDocumentAttr:function(m){this._set("ownerDocument",
m)},attributeMap:{},_blankGif:c.blankGif||h.toUrl("dojo/resources/blank.gif"),postscript:function(m,a){this.create(m,a)},create:function(m,a){this.srcNodeRef=e.byId(a);this._connects=[];this._supportingWidgets=[];if(this.srcNodeRef&&"string"==typeof this.srcNodeRef.id)this.id=this.srcNodeRef.id;if(m)this.params=m,o.mixin(this,m);this.postMixInProperties();if(!this.id)this.id=q.getUniqueId(this.declaredClass.replace(/\./g,"_")),this.params&&delete this.params.id;this.ownerDocument=this.ownerDocument||
(this.srcNodeRef?this.srcNodeRef.ownerDocument:t.doc);this.ownerDocumentBody=t.body(this.ownerDocument);q.add(this);this.buildRendering();var d;if(this.domNode){this._applyAttributes();var b=this.srcNodeRef;b&&b.parentNode&&this.domNode!==b&&(b.parentNode.replaceChild(this.domNode,b),d=!0);this.domNode.setAttribute("widgetId",this.id)}this.postCreate();d&&delete this.srcNodeRef;this._created=!0},_applyAttributes:function(){var m=this.constructor,a=m._setterAttrs;if(!a){var a=m._setterAttrs=[],d;for(d in this.attributeMap)a.push(d);
var m=m.prototype,b;for(b in m)b in this.attributeMap||"_set"+b.replace(/^[a-z]|-[a-zA-Z]/g,function(a){return a.charAt(a.length-1).toUpperCase()})+"Attr"in m&&a.push(b)}j.forEach(a,function(a){this.params&&a in this.params||this[a]&&this.set(a,this[a])},this);for(var k in this.params)this.set(k,this.params[k])},postMixInProperties:function(){},buildRendering:function(){if(!this.domNode)this.domNode=this.srcNodeRef||this.ownerDocument.createElement("div");if(this.baseClass){var a=this.baseClass.split(" ");
this.isLeftToRight()||(a=a.concat(j.map(a,function(a){return a+"Rtl"})));f.add(this.domNode,a)}},postCreate:function(){},startup:function(){if(!this._started)this._started=!0,j.forEach(this.getChildren(),function(a){if(!a._started&&!a._destroyed&&o.isFunction(a.startup))a.startup(),a._started=!0})},destroyRecursive:function(a){this._beingDestroyed=!0;this.destroyDescendants(a);this.destroy(a)},destroy:function(a){function b(d){d.destroyRecursive?d.destroyRecursive(a):d.destroy&&d.destroy(a)}this._beingDestroyed=
!0;this.uninitialize();j.forEach(this._connects,o.hitch(this,"disconnect"));j.forEach(this._supportingWidgets,b);j.forEach(q.findWidgets(this.domNode,this.containerNode),b);this.destroyRendering(a);q.remove(this.id);this._destroyed=!0},destroyRendering:function(a){this.bgIframe&&(this.bgIframe.destroy(a),delete this.bgIframe);this.domNode&&(a?l.remove(this.domNode,"widgetId"):b.destroy(this.domNode),delete this.domNode);this.srcNodeRef&&(a||b.destroy(this.srcNodeRef),delete this.srcNodeRef)},destroyDescendants:function(a){j.forEach(this.getChildren(),
function(d){d.destroyRecursive&&d.destroyRecursive(a)})},uninitialize:function(){return!1},_setStyleAttr:function(a){var b=this.domNode;o.isObject(a)?d.set(b,a):b.style.cssText=b.style.cssText?b.style.cssText+("; "+a):a;this._set("style",a)},_attrToDom:function(a,b,d){d=3<=arguments.length?d:this.attributeMap[a];j.forEach(o.isArray(d)?d:[d],function(d){var k=this[d.node||d||"domNode"];switch(d.type||"attribute"){case "attribute":o.isFunction(b)&&(b=o.hitch(this,b));d=d.attribute?d.attribute:/^on[A-Z][a-zA-Z]*$/.test(a)?
a.toLowerCase():a;k.tagName?l.set(k,d,b):k.set(d,b);break;case "innerText":k.innerHTML="";k.appendChild(this.ownerDocument.createTextNode(b));break;case "innerHTML":k.innerHTML=b;break;case "class":f.replace(k,b,this[a])}},this)},get:function(a){var d=this._getAttrNames(a);return this[d.g]?this[d.g]():this[a]},set:function(a,d){if("object"===typeof a){for(var b in a)this.set(b,a[b]);return this}b=this._getAttrNames(a);var k=this[b.s];if(o.isFunction(k))var f=k.apply(this,Array.prototype.slice.call(arguments,
1));else{var k=this.focusNode&&!o.isFunction(this.focusNode)?"focusNode":"domNode",g=this[k].tagName,c;if(!(c=v[g])){c=this[k];var e={},p;for(p in c)e[p.toLowerCase()]=!0;c=v[g]=e}p=a in this.attributeMap?this.attributeMap[a]:b.s in this?this[b.s]:b.l in c&&"function"!=typeof d||/^aria-|^data-|^role$/.test(a)?k:null;null!=p&&this._attrToDom(a,d,p);this._set(a,d)}return f||this},_attrPairNames:{},_getAttrNames:function(a){var d=this._attrPairNames;if(d[a])return d[a];var b=a.replace(/^[a-z]|-[a-zA-Z]/g,
function(a){return a.charAt(a.length-1).toUpperCase()});return d[a]={n:a+"Node",s:"_set"+b+"Attr",g:"_get"+b+"Attr",l:b.toLowerCase()}},_set:function(a,d){var b=this[a];this[a]=d;this._created&&d!==b&&(this._watchCallbacks&&this._watchCallbacks(a,b,d),this.emit("attrmodified-"+a,{detail:{prevValue:b,newValue:d}}))},emit:function(a,d,b){d=d||{};if(void 0===d.bubbles)d.bubbles=!0;if(void 0===d.cancelable)d.cancelable=!0;if(!d.detail)d.detail={};d.detail.widget=this;var k,c=this["on"+a];c&&(k=c.apply(this,
b?b:d));this._started&&!this._beingDestroyed&&r.emit(this.domNode,a.toLowerCase(),d);return k},on:function(a,d){var b=this._onMap(a);return b?i.after(this,b,d,!0):this.own(r(this.domNode,a,d))[0]},_onMap:function(a){var d=this.constructor,b=d._onMap;if(!b){var b=d._onMap={},k;for(k in d.prototype)/^on/.test(k)&&(b[k.replace(/^on/,"").toLowerCase()]=k)}return b[a.toLowerCase()]},toString:function(){return"[Widget "+this.declaredClass+", "+(this.id||"NO ID")+"]"},getChildren:function(){return this.containerNode?
q.findWidgets(this.containerNode):[]},getParent:function(){return q.getEnclosingWidget(this.domNode.parentNode)},connect:function(d,b,k){return this.own(a.connect(d,b,this,k))[0]},disconnect:function(a){a.remove()},subscribe:function(a,d){return this.own(x.subscribe(a,o.hitch(this,d)))[0]},unsubscribe:function(a){a.remove()},isLeftToRight:function(){return this.dir?"ltr"==this.dir:n.isBodyLtr(this.ownerDocument)},isFocusable:function(){return this.focus&&"none"!=d.get(this.domNode,"display")},placeAt:function(a,
d){var k=!a.tagName&&q.byId(a);k&&k.addChild&&(!d||"number"===typeof d)?k.addChild(this,d):(k=k?k.containerNode&&!/after|before|replace/.test(d||"")?k.containerNode:k.domNode:e.byId(a,this.ownerDocument),b.place(this.domNode,k,d),!this._started&&(this.getParent()||{})._started&&this.startup());return this},getTextDir:function(a,d){return d},applyTextDir:function(){},defer:function(a,d){var b=setTimeout(o.hitch(this,function(){b=null;this._destroyed||o.hitch(this,a)()}),d||0);return{remove:function(){b&&
(clearTimeout(b),b=null);return null}}}})})},"dojo/Stateful":function(){define("dojo/Stateful",["./_base/declare","./_base/lang","./_base/array","dojo/when"],function(h,j,i,c){return h("dojo.Stateful",null,{_attrPairNames:{},_getAttrNames:function(a){var c=this._attrPairNames;return c[a]?c[a]:c[a]={s:"_"+a+"Setter",g:"_"+a+"Getter"}},postscript:function(a){a&&this.set(a)},_get:function(a,c){return"function"===typeof this[c.g]?this[c.g]():this[a]},get:function(a){return this._get(a,this._getAttrNames(a))},
set:function(a,g){if("object"===typeof a){for(var e in a)a.hasOwnProperty(e)&&this.set(e,a[e]);return this}e=this._getAttrNames(a);var h=this._get(a,e);e=this[e.s];var f;"function"===typeof e?f=e.apply(this,Array.prototype.slice.call(arguments,1)):this[a]=g;if(this._watchCallbacks){var b=this;c(f,function(){b._watchCallbacks(a,h,g)})}return this},_changeAttrValue:function(a,c){var e=this.get(a);this[a]=c;this._watchCallbacks&&this._watchCallbacks(a,e,c);return this},watch:function(a,c){var e=this._watchCallbacks;
if(!e)var h=this,e=this._watchCallbacks=function(a,d,b,c){var f=function(c){if(c)for(var c=c.slice(),f=0,e=c.length;f<e;f++)c[f].call(h,a,d,b)};f(e["_"+a]);c||f(e["*"])};!c&&"function"===typeof a?(c=a,a="*"):a="_"+a;var f=e[a];"object"!==typeof f&&(f=e[a]=[]);f.push(c);var b={};b.unwatch=b.remove=function(){var a=i.indexOf(f,c);-1<a&&f.splice(a,1)};return b}})})},"dijit/Destroyable":function(){define("dijit/Destroyable",["dojo/_base/array","dojo/aspect","dojo/_base/declare"],function(h,j,i){return i("dijit.Destroyable",
null,{destroy:function(){this._destroyed=!0},own:function(){h.forEach(arguments,function(c){var a="destroyRecursive"in c?"destroyRecursive":"destroy"in c?"destroy":"remove";c._odh=j.before(this,"destroy",function(g){c._odh.remove();c[a](g)});j.after(c,a,function(){c._odh.remove()})},this);return arguments}})})},"dijit/registry":function(){define("dijit/registry",["dojo/_base/array","dojo/sniff","dojo/_base/unload","dojo/_base/window","./main"],function(h,j,i,c,a){var g={},e={},l={length:0,add:function(a){if(e[a.id])throw Error("Tried to register widget with id=="+
a.id+" but that id is already registered");e[a.id]=a;this.length++},remove:function(a){e[a]&&(delete e[a],this.length--)},byId:function(a){return"string"==typeof a?e[a]:a},byNode:function(a){return e[a.getAttribute("widgetId")]},toArray:function(){var a=[],b;for(b in e)a.push(e[b]);return a},getUniqueId:function(c){var b;do b=c+"_"+(c in g?++g[c]:g[c]=0);while(e[b]);return"dijit"==a._scopeName?b:a._scopeName+"_"+b},findWidgets:function(a,b){function c(a){for(a=a.firstChild;a;a=a.nextSibling)if(1==
a.nodeType){var g=a.getAttribute("widgetId");g?(g=e[g])&&d.push(g):a!==b&&c(a)}}var d=[];c(a);return d},_destroyAll:function(){a._curFocus=null;a._prevFocus=null;a._activeStack=[];h.forEach(l.findWidgets(c.body()),function(a){a._destroyed||(a.destroyRecursive?a.destroyRecursive():a.destroy&&a.destroy())})},getEnclosingWidget:function(a){for(;a;){var b=a.getAttribute&&a.getAttribute("widgetId");if(b)return e[b];a=a.parentNode}return null},_hash:e};return a.registry=l})},"dojo/_base/unload":function(){define("dojo/_base/unload",
["./kernel","./lang","../on"],function(h,j,i){var c=window,a={addOnWindowUnload:function(a,e){if(!h.windowUnloaded)i(c,"unload",h.windowUnloaded=function(){});i(c,"unload",j.hitch(a,e))},addOnUnload:function(a,e){i(c,"beforeunload",j.hitch(a,e))}};h.addOnWindowUnload=a.addOnWindowUnload;h.addOnUnload=a.addOnUnload;return a})},"dijit/main":function(){define("dijit/main",["dojo/_base/kernel"],function(h){return h.dijit})},"dijit/_TemplatedMixin":function(){define("dijit/_TemplatedMixin","dojo/_base/lang,dojo/touch,./_WidgetBase,dojo/string,dojo/cache,dojo/_base/array,dojo/_base/declare,dojo/dom-construct,dojo/sniff,dojo/_base/unload".split(","),
function(h,j,i,c,a,g,e,l,f,b){var n=e("dijit._TemplatedMixin",null,{templateString:null,templatePath:null,_skipNodeCache:!1,_earlyTemplatedStartup:!1,constructor:function(){this._attachPoints=[];this._attachEvents=[]},_stringRepl:function(a){var b=this.declaredClass,e=this;return c.substitute(a,this,function(a,d){"!"==d.charAt(0)&&(a=h.getObject(d.substr(1),!1,e));if("undefined"==typeof a)throw Error(b+" template:"+d);return null==a?"":"!"==d.charAt(0)?a:a.toString().replace(/"/g,"&quot;")},this)},
buildRendering:function(){if(!this.templateString)this.templateString=a(this.templatePath,{sanitize:!0});var d=n.getCachedTemplate(this.templateString,this._skipNodeCache,this.ownerDocument),b;if(h.isString(d)){if(b=l.toDom(this._stringRepl(d),this.ownerDocument),1!=b.nodeType)throw Error("Invalid template: "+d);}else b=d.cloneNode(!0);this.domNode=b;this.inherited(arguments);this._attachTemplateNodes(b,function(a,d){return a.getAttribute(d)});this._beforeFillContent();this._fillContent(this.srcNodeRef)},
_beforeFillContent:function(){},_fillContent:function(a){var b=this.containerNode;if(a&&b)for(;a.hasChildNodes();)b.appendChild(a.firstChild)},_attachTemplateNodes:function(a,b){for(var c=h.isArray(a)?a:a.all||a.getElementsByTagName("*"),e=h.isArray(a)?0:-1;0>e||c[e];e++){var g=-1==e?a:c[e];if(!this.widgetsInTemplate||!b(g,"dojoType")&&!b(g,"data-dojo-type")){var f=b(g,"dojoAttachPoint")||b(g,"data-dojo-attach-point");if(f)for(var i=f.split(/\s*,\s*/);f=i.shift();)h.isArray(this[f])?this[f].push(g):
this[f]=g,this._attachPoints.push(f);if(f=b(g,"dojoAttachEvent")||b(g,"data-dojo-attach-event"))for(var i=f.split(/\s*,\s*/),n=h.trim;f=i.shift();)if(f){var l=null;-1!=f.indexOf(":")?(l=f.split(":"),f=n(l[0]),l=n(l[1])):f=n(f);l||(l=f);this._attachEvents.push(this.connect(g,j[f]||f,l))}}}},destroyRendering:function(){g.forEach(this._attachPoints,function(a){delete this[a]},this);this._attachPoints=[];g.forEach(this._attachEvents,this.disconnect,this);this._attachEvents=[];this.inherited(arguments)}});
n._templateCache={};n.getCachedTemplate=function(a,b,e){var g=n._templateCache,f=a,h=g[f];if(h){try{if(!h.ownerDocument||h.ownerDocument==(e||document))return h}catch(i){}l.destroy(h)}a=c.trim(a);if(b||a.match(/\$\{([^\}]+)\}/g))return g[f]=a;b=l.toDom(a,e);if(1!=b.nodeType)throw Error("Invalid template: "+a);return g[f]=b};f("ie")&&b.addOnWindowUnload(function(){var a=n._templateCache,b;for(b in a){var c=a[b];"object"==typeof c&&l.destroy(c);delete a[b]}});h.extend(i,{dojoAttachEvent:"",dojoAttachPoint:""});
return n})},"dojo/touch":function(){define("dojo/touch","./_base/kernel,./_base/lang,./aspect,./dom,./on,./has,./mouse,./ready,./_base/window".split(","),function(h,j,i,c,a,g,e,l,f){function b(b){return function(d,c){return a(d,b,c)}}var i=g("touch"),n,d;i&&(l(function(){d=f.body();f.doc.addEventListener("touchstart",function(b){var c=d;d=b.target;a.emit(c,"dojotouchout",{target:c,relatedTarget:d,bubbles:!0});a.emit(d,"dojotouchover",{target:d,relatedTarget:c,bubbles:!0})},!0);a(f.doc,"touchmove",
function(b){var c=d;d=f.doc.elementFromPoint(b.pageX-f.body().parentNode.scrollLeft,b.pageY-f.body().parentNode.scrollTop);c!==d&&(a.emit(c,"dojotouchout",{target:c,relatedTarget:d,bubbles:!0}),a.emit(d,"dojotouchover",{target:d,relatedTarget:c,bubbles:!0}))})}),n=function(b,e){return a(f.doc,"touchmove",function(a){(b===f.doc||c.isDescendant(d,b))&&e.call(this,j.mixin({},a,{target:d}))})});e={press:b(i?"touchstart":"mousedown"),move:i?n:b("mousemove"),release:b(i?"touchend":"mouseup"),cancel:i?b("touchcancel"):
e.leave,over:b(i?"dojotouchover":"mouseover"),out:b(i?"dojotouchout":"mouseout"),enter:e._eventHandler(i?"dojotouchover":"mouseover"),leave:e._eventHandler(i?"dojotouchout":"mouseout")};return h.touch=e})},"dojo/string":function(){define("dojo/string",["./_base/kernel","./_base/lang"],function(h,j){var i={};j.setObject("dojo.string",i);i.rep=function(c,a){if(0>=a||!c)return"";for(var g=[];;){a&1&&g.push(c);if(!(a>>=1))break;c+=c}return g.join("")};i.pad=function(c,a,g,e){g||(g="0");c=""+c;a=i.rep(g,
Math.ceil((a-c.length)/g.length));return e?c+a:a+c};i.substitute=function(c,a,g,e){e=e||h.global;g=g?j.hitch(e,g):function(a){return a};return c.replace(/\$\{([^\s\:\}]+)(?:\:([^\s\:\}]+))?\}/g,function(c,f,b){c=j.getObject(f,!1,a);b&&(c=j.getObject(b,!1,e).call(e,c,f));return g(c,f).toString()})};i.trim=String.prototype.trim?j.trim:function(c){for(var c=c.replace(/^\s+/,""),a=c.length-1;0<=a;a--)if(/\S/.test(c.charAt(a))){c=c.substring(0,a+1);break}return c};return i})},"dojo/cache":function(){define("dojo/cache",
["./_base/kernel","./text"],function(h){return h.cache})},"dojo/text":function(){define("dojo/text",["./_base/kernel","require","./has","./_base/xhr"],function(h,j,i,c){var a;a=function(a,e,d){c("GET",{url:a,sync:!!e,load:d,headers:h.config.textPluginHeaders||{}})};var g={},e=function(a){if(a){var a=a.replace(/^\s*<\?xml(\s)+version=[\'\"](\d)*.(\d)*[\'\"](\s)*\?>/im,""),c=a.match(/<body[^>]*>\s*([\s\S]+)\s*<\/body>/im);c&&(a=c[1])}else a="";return a},l={},f={};h.cache=function(b,c,d){var f;"string"==
typeof b?/\//.test(b)?(f=b,d=c):f=j.toUrl(b.replace(/\./g,"/")+(c?"/"+c:"")):(f=b+"",d=c);b=void 0!=d&&"string"!=typeof d?d.value:d;d=d&&d.sanitize;if("string"==typeof b)return g[f]=b,d?e(b):b;if(null===b)return delete g[f],null;f in g||a(f,!0,function(a){g[f]=a});return d?e(g[f]):g[f]};return{dynamic:!0,normalize:function(a,c){var d=a.split("!"),e=d[0];return(/^\./.test(e)?c(e):e)+(d[1]?"!"+d[1]:"")},load:function(b,c,d){var b=b.split("!"),h=1<b.length,i=b[0],j=c.toUrl(b[0]),b=l,r=function(a){d(h?
e(a):a)};i in g?b=g[i]:j in c.cache?b=c.cache[j]:j in g&&(b=g[j]);if(b===l)if(f[j])f[j].push(r);else{var s=f[j]=[r];a(j,!c.async,function(a){g[i]=g[j]=a;for(var b=0;b<s.length;)s[b++](a);delete f[j]})}else r(b)}}})},"dijit/_Container":function(){define("dijit/_Container",["dojo/_base/array","dojo/_base/declare","dojo/dom-construct","./registry"],function(h,j,i){return j("dijit._Container",null,{buildRendering:function(){this.inherited(arguments);if(!this.containerNode)this.containerNode=this.domNode},
addChild:function(c,a){var g=this.containerNode;if(a&&"number"==typeof a){var e=this.getChildren();if(e&&e.length>=a)g=e[a-1].domNode,a="after"}i.place(c.domNode,g,a);this._started&&!c._started&&c.startup()},removeChild:function(c){"number"==typeof c&&(c=this.getChildren()[c]);if(c)(c=c.domNode)&&c.parentNode&&c.parentNode.removeChild(c)},hasChildren:function(){return 0<this.getChildren().length},_getSiblingOfChild:function(c,a){var g=this.getChildren(),e=h.indexOf(this.getChildren(),c);return g[e+
a]},getIndexOfChild:function(c){return h.indexOf(this.getChildren(),c)}})})}}});define("ololo/dijitcore",[],1);